version: "3.18"
services:
  service-alerts:
    image: timurshyk/service-alerts-server
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://backend:8080/actuator/health" ]
