server:
  port: 8888

alert-api:
  out-path: ./app/resources/alerts.list
  in-path: ./app/resources/alerts.list
  zone-id: "Europe/Warsaw"
  actual-filter: true

springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/ui"
